#Reyes Lugo Luz Daniela

print("\n---Ejercicio 01---\n")
nombre = input("Ingrese su nombre: ")
telefono = input("Ingrese su número telefonico: ")
direccion = input("Ingrese su dirección: ")
edad = (int)(input("Ingrese su edad: "))
nacionalidad = input("Ingrese su nacionalidad: ")
nacimiento = input("Ingrese su fecha de nacimiento: ")
altura = (float)(input("Ingrese su altura: "))
peso = (float)(input("Ingrese su peso: "))

print("\n---DATOS---\n")
print("Nombre: "+ nombre +". Tipo de dato: ")
print(type(nombre))
print("Número telefonico: "+ telefono +". Tipo de dato: ")
print(type(telefono))
print("Dirección: "+ direccion +". Tipo de dato: ")
print(type(direccion))
print("Edad: "+ str(edad) +". Tipo de dato: ")
print(type(edad))
print("Nacionalidad: " + nacionalidad +". Tipo de dato: ")
print(type(nacionalidad))
print("Fecha de nacimiento: "+ nacimiento +". Tipo de dato: ")
print(type(nacimiento))
print("Altura: "+ str(altura) +". Tipo de dato: ")
print(type(altura))
print("Peso: "+ str(peso) +". Tipo de dato: ")
print(type(peso))
